node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     sh 'npm test'
   }
   stage('docker build/push') {
     docker.withRegistry('https://registry-1.docker.io/v2/', 'dockerhub') {
       def app = docker.build("ydlkdevops/docker-demo:${commit_id}", '.').push()
     }
   }
}
